version: "3"
services:
    telegram-sender:
        container_name: "telegram-sender-node"
        build: .
        volumes:
            - ./src:/opt/app
        working_dir: /opt/app
        env_file: env.env
        command: npm start
